version: '3.8'

services:
  fitness-db:
    image: mysql:8.0
    container_name: fitness_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness_app
      MYSQL_USER: fitness
      MYSQL_PASSWORD: fitness
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
